CREATE TABLE `tableName` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `create_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
  `status` TINYINT DEFAULT 1 COMMENT '数据状态',



  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;